### ISSUE TITLE
Add AMPT to ImageJ list of update sites

### ISSUE THREAD

**Issue by APatrickJ** [AllenMLI/AMPT#115]
Add AMPT to this page: https://imagej.net/list-of-update-sites/

Per the instructions, this requires an update to this file: https://github.com/imagej/list-of-update-sites/blob/main/sites.yml

**Name:** AMPT
**Site:** https://sites.imagej.net/AMPT/
**Description:** The [Aquatic Mammal Photogrammetry Tool (AMPT)](https://github.com/AllenMLI/AMPT) is an ImageJ plug-in that simplifies the process of measuring aquatic mammals from aerial imagery. The tool may be configured to support different guided measurements.
**Maintainer:** [AMPT Developers](mailto:ampt-dev@allenai.org)

**Comment by palbee** [comment]
Pull requests have been submitted to the ImageJ folks for listing the update site and adding a wikipage.

- [ ] [Added AMPT](https://github.com/imagej/list-of-update-sites/pull/99)
- [ ] [Add plugin information for AMPT](https://github.com/imagej/imagej.github.io/pull/215)
